server:
  port: 9091
spring:
  application:
    name: WapSoft
  profiles:
    active: test
    
---  
spring:
  profiles: dev
  
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wapsoft
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace   
        dialect: org.hibernate.dialect.MySQL5Dialect
        connection.pool_size: 10

---
spring:
  profiles: test
  
  h2:
    console:
      enabled: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

---
spring:
  profiles: prod
  
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace   
        dialect: org.hibernate.dialect.MySQL5Dialect
        connection.pool_size: 10